version: '2'
services:
  ptm01-app:
    image: ptm01
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ptm01-postgresql:5432/ptm01
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  ptm01-postgresql:
    extends:
      file: postgresql.yml
      service: ptm01-postgresql
